In [0]:
# Import libraries

import numpy as np
import pandas as pd

In [2]:
from google.colab import files

uploaded = files.upload()

Saving hrdata_ver03.csv to hrdata_ver03 (1).csv


In [0]:
df = pd.read_csv('hrdata_ver03.csv')

In [8]:
df.head()

Serial Number  Gender  Age Action  Exp Action  SUP-Gender  SUP-Age Action  \
0         A4338       1   25.934247    1.336986           2       35.443836   
1         A3673       1   22.520548    0.000000           2       31.358904   
2           A83       0   60.126027   31.435616           1       33.602740   
3           A95       0   55.619178   31.517808           1       47.443836   
4          A113       0   56.038356   31.186301           1       37.605479   

   SUP-Exp Action  Re-Entry  MPT  Ed Allowance        ...         Resign  \
0       13.345205         1    1             0        ...              1   
1        5.087671         0    1             0        ...              1   
2       10.090411         0    0             0        ...              0   
3       27.849315         0    0             0        ...              0   
4        8.920548         0    0             0        ...              0   

   VAC_Dependent Care  VAC_Maternity  VAC_Others  VAC_Personal  VAC_Sick  \
0                 0.0            0.0         0.0           0.0      0.75   
1                 0.0            0.0         0.0           0.0      0.00   
2                 0.0            0.0         0.0           0.0      0.00   
3                 0.0            0.0         0.0           0.0      0.00   
4                 0.0            0.0         0.0           0.0      0.00   

   VAC_Vacation  STEM  Max Degree  Last Grad Action  
0          1.67     0           3               0.0  
1          0.00     0           2               0.0  
2          0.00     0           0               0.0  
3          0.00     0           0               0.0  
4          0.00     0           0               0.0  

[5 rows x 21 columns]

In [0]:
#dfEduInstituteGroup = pd.get_dummies(df['Max_EduInstituteGroup'], prefix='Max_EduInstituteGroup')
#dfHireTypeGroup = pd.get_dummies(df['HireType'], prefix='HireType')
#dfHireSourceGroup = pd.get_dummies(df['HireSourceGroup'], prefix='HireSourceGroup')

#df = pd.concat([df, dfEduInstituteGroup,dfHireTypeGroup,dfHireSourceGroup], axis=1)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
#df_train = df[df['ActionYear'] < 2017]
#df_test = df[ df['ActionYear'] >= 2017]
#df_train.shape

In [0]:
#df_train_variable = df_train.drop(['SerialNumber','ActionYear','Leave','Max_EduInstituteGroup','HireType','HireSourceGroup'],axis=1)
#df_train_label = df_train['Leave']

#df_test_variable = df_test.drop(['SerialNumber','ActionYear','Leave','Max_EduInstituteGroup','HireType','HireSourceGroup'],axis=1)
#df_test_label = df_test['Leave']

In [0]:
#X_Train, X_Test, Y_Train, Y_Test = df_train_variable, df_test_variable, df_train_label, df_test_label

In [0]:
X = df.drop('Resign',axis=1)
X = X.drop('Serial Number',axis=1)
Y = df['Resign']
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size=0.4)

# **Logistic Regression**

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
lr = LogisticRegression(C=1.0)
lr_Model = lr.fit(X_Train,Y_Train)

In [0]:
lr_Pred = lr.predict(X_Test)

In [30]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_Test,lr_Pred))

             precision    recall  f1-score   support

          0       0.79      0.80      0.80      1194
          1       0.71      0.70      0.70       818

avg / total       0.76      0.76      0.76      2012



# **Naive Bayes**

In [0]:
from sklearn.naive_bayes import GaussianNB

In [0]:
gnb = GaussianNB()
gnb_Model = gnb.fit(X_Train,Y_Train)

In [0]:
gnb_Predict = gnb_Model.predict(X_Test)

In [34]:
print(classification_report(Y_Test,gnb_Predict))

             precision    recall  f1-score   support

          0       0.84      0.64      0.73      1194
          1       0.61      0.82      0.70       818

avg / total       0.75      0.72      0.72      2012



# **RandomForest**

In [35]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_Train, Y_Train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [0]:
rfd_Pred = rfc.predict(X_Test)

In [37]:
confusion_matrix(Y_Test,rfd_Pred)

array([[1049,  145],
       [ 193,  625]])

In [38]:
print(classification_report(Y_Test,rfd_Pred))

             precision    recall  f1-score   support

          0       0.84      0.88      0.86      1194
          1       0.81      0.76      0.79       818

avg / total       0.83      0.83      0.83      2012



# **SVM**


In [0]:
from sklearn import svm

In [49]:
svmModel = svm.SVC()
svmModel.fit(X_Train, Y_Train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
svm_Pred = svmModel.predict(X_Test)

In [51]:
confusion_matrix(Y_Test,svm_Pred)

array([[1010,  184],
       [ 310,  508]])

In [52]:
print(classification_report(Y_Test,svm_Pred))

             precision    recall  f1-score   support

          0       0.77      0.85      0.80      1194
          1       0.73      0.62      0.67       818

avg / total       0.75      0.75      0.75      2012



# **XGBoost**

In [0]:
!pip install -q xgboost==0.4a30

In [0]:
import xgboost as xgb

In [62]:
gbm = xgb.XGBClassifier(max_depth=3, n_estimators=300, learning_rate=0.05).fit(X_Train, Y_Train)
predictions = gbm.predict(X_Test)
print(classification_report(Y_Test,predictions))

             precision    recall  f1-score   support

          0       0.85      0.87      0.86      1194
          1       0.80      0.77      0.78       818

avg / total       0.83      0.83      0.83      2012



/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


# **Voting Ensemble**

In [0]:
from sklearn.ensemble import VotingClassifier
from sklearn import cross_validation

In [0]:
clf1 = LogisticRegression()
clf2 = RandomForestClassifier()
clf3 = GaussianNB()
clf4 = xgb.XGBClassifier(max_depth=3, n_estimators=300, learning_rate=0.05)

In [65]:
for clf, label in zip([clf1, clf2, clf3,clf4], ['Logistic Regression', 'Random Forest', 'naive Bayes','XGBoost']):

    scores = cross_validation.cross_val_score(clf, X_Train, Y_Train, cv=5, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))

Accuracy: 0.75 (+/- 0.02) [Logistic Regression]
Accuracy: 0.79 (+/- 0.02) [Random Forest]
Accuracy: 0.70 (+/- 0.02) [naive Bayes]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this wi

Accuracy: 0.82 (+/- 0.01) [XGBoost]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [66]:
#Hard Vote
eclf1 = VotingClassifier(estimators=[
        ('lr', clf1), ('rf', clf2), ('gnb', clf3),('xgb',clf4)], voting='hard')
eclf1 = eclf1.fit(X_Train, Y_Train)
eclf1_Pred =eclf1.predict(X_Test)
print(eclf1_Pred)

# Soft Vote
eclf2 = VotingClassifier(estimators=[
        ('lr', clf1), ('rf', clf2), ('gnb', clf3)],
        voting='soft')
eclf2 = eclf2.fit(X_Train, Y_Train)
eclf2_Pred =eclf2.predict(X_Test)
print(eclf2_Pred)

#mock Weight
eclf3 = VotingClassifier(estimators=[
       ('lr', clf1), ('rf', clf2), ('gnb', clf3)],
       voting='soft', weights=[2,1,1],
       flatten_transform=True)
eclf3 = eclf3.fit(X_Train, Y_Train)
eclf3_Pred =eclf3.predict(X_Test)
print(eclf3_Pred)

[1 1 0 ... 1 0 1]
[1 1 0 ... 1 0 1]
[1 1 0 ... 1 0 1]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this wi

In [67]:
print(classification_report(Y_Test,eclf1_Pred))

             precision    recall  f1-score   support

          0       0.81      0.88      0.85      1194
          1       0.80      0.71      0.75       818

avg / total       0.81      0.81      0.81      2012



In [44]:
print(classification_report(Y_Test,eclf2_Pred))

             precision    recall  f1-score   support

          0       0.84      0.74      0.79      1194
          1       0.68      0.79      0.73       818

avg / total       0.77      0.76      0.76      2012



In [45]:
print(classification_report(Y_Test,eclf3_Pred))

             precision    recall  f1-score   support

          0       0.83      0.75      0.79      1194
          1       0.68      0.77      0.72       818

avg / total       0.77      0.76      0.76      2012

